kind = "web"
previewPath = "/"
title = "Alman & Terii Wedding Invitation"
version = "1.0.0"
id = "artifacts/wedding-invitation"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19315

[services.development]
run = "node server.js"

[services.production]
serve = "static"
publicDir = "artifacts/wedding-invitation/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19315"
BASE_PATH = "/"
